# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [1]:
import numpy as np

In [5]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
array_numpy = np.arange(1000000)
array_list = list(range(1000000))

%time for _ in range(10): array_numpy_2 = array_numpy * 2
%time for _ in range(10): array_list_2 = [x * 2 for x in array_list]

Wall time: 24 ms
Wall time: 875 ms


### Exercício 2

In [10]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

arr_10 = np.array(np.arange(10))
print(arr_10)

#for x in arr_10:
#    if x >= 5 and x <= 8:
#        arr_10[x] = 0
arr_10[5:9] = 0

print(arr_10)
print(type(arr_10))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 0 9]
<class 'numpy.ndarray'>


### Exercício 3

In [12]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
arr3d = np.array([[5,4,6],[8,7,4],[12,5,57]])
print(arr3d[0])

[5 4 6]


In [11]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [14]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matriz = np.array([[1, 5, 8], [12, 17, 18], [7, 8, 9]])
print(matriz[2])
print(matriz[:2, 1:])

[7 8 9]
[[ 5  8]
 [17 18]]


### Exercício 5

In [16]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print(arr)
print()
print(np.transpose(arr))
print()
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [17]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

for x in range(len(cond)):
    if cond[x] == True:
        print(xarr[x])
    else:
        print(yarr[x])

1.1
2.2
1.3
1.4
2.5


In [18]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [19]:
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [20]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
arr_a = np.array(np.arange(10))
print('A:', arr_a)
np.save('array_a', arr_a)
arr_b = np.load('array_a.npy')
print('B:', arr_b)

A: [0 1 2 3 4 5 6 7 8 9]
B: [0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [21]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
print(set(obj))

{'c', 'd', 'a', 'b'}


In [22]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [23]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [24]:
df = pd.read_json(url)
# index, number 16, title 16, labels 15, state 14
df = df.loc[:, ['number', 'title', 'labels', 'state']]
df.head()

number                                              title  \
0   24760  Pandas Test Scripts always fail tried 0.24.0rc...   
1   24759  BUG: DataFrame.min/max with axis=1 and uniform...   
2   24758      COMPAT: Properly encode filenames in read_csv   
3   24757  implement+test mean for datetimelike EA/Index/...   
4   24753     [0.24.0rc1] passing dtype='M8' to Index raises   

                                              labels state  
0                                                 []  open  
1  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2  [{'id': 49747336, 'node_id': 'MDU6TGFiZWw0OTc0...  open  
3  [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open  
4  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open

In [25]:
data = resp.json()
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    24760  Pandas Test Scripts always fail tried 0.24.0rc...   
1    24759  BUG: DataFrame.min/max with axis=1 and uniform...   
2    24758      COMPAT: Properly encode filenames in read_csv   
3    24757  implement+test mean for datetimelike EA/Index/...   
4    24753     [0.24.0rc1] passing dtype='M8' to Index raises   
5    24752  DataFrame.mean includes datetime64[ns] dtypes ...   
6    24751  CategoricalAccessor.categorical removed in 0.2...   
7    24749                       Split test_excel.py (#24472)   
8    24748  ENH / RFC Only apply first row once in fast apply   
9    24742  23 seems to be the new 42: exception if concat...   
10   24740     Exception when grouping on a modified category   
11   24739  0.24.0rc1: infer_dtype(DatetimeIndex) returns ...   
12   24737  PERF: leverage tzlocal package to provide 2000...   
13   24736  TST: add  coverage of DST transition for DateT...   
14   24735  PERF: fix some of .clip() performance regressi...   
15   24734  read_excel and read_csv doesn't read the entir...   
16   24733      BUG-24212 fix usage of Index.take in pd.merge   
17   24732  BUG: Prevent 3D-ndarray for nested tuple label...   
18   24730                           changing order of keys?    
19   24729  Multiple unstack in multi level columns DataFrame   
20   24728  corr return without duplicates and sorted by c...   
21   24727                                  Doc make.py clean   
22   24725  BUG: Switched shapes in ValueError msg in Data...   
23   24721  CLN: replace %s syntax with .format in pandas....   
24   24718  BUG: Offset-based rolling window, with only on...   
25   24716  DataFrame.to_xarray produces FutureWarning for...   
26   24715  DOC: Implementing redirect system, and adding ...   
27   24713     Should DatetimeTZDtype normalize the timezone?   
28   24712                     IMPL DTA should *only* hold i8   
29   24711     Please consider switch to standard json module   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2   [{'id': 49747336, 'node_id': 'MDU6TGFiZWw0OTc0...  open  
3   [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open  
4   [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
5   [{'id': 47223669, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
6   [{'id': 77550281, 'node_id': 'MDU6TGFiZWw3NzU1...  open  
7   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
8   [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
9   [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
10  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
11  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
12  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
13  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
14  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
15  [{'id': 2301354, 'node_id': 'MDU6TGFiZWwyMzAxM...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzM...  open  
18  [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open  
19  [{'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2...  open  
20  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
21  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
22  [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
23  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25  [{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4ND...  open  
26  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
27  [{'id': 60458168, 'node_id': 'MDU6TGFiZWw2MDQ1...  open  
28  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
29  [{'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3...  open

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3

# conectando...
conn = sqlite3.connect('clientes.db')
# definindo um cursor
cursor = conn.cursor()

# criando a tabela (schema)
cursor.execute("""
CREATE TABLE clientes (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        idade INTEGER,
        cpf     VARCHAR(11) NOT NULL,
        email TEXT NOT NULL,
        fone TEXT,
        cidade TEXT,
        uf VARCHAR(2) NOT NULL,
        criado_em DATE NOT NULL
);
""")

# inserindo dados na tabela
cursor.execute("""
INSERT INTO clientes (nome, idade, cpf, email, fone, cidade, uf, criado_em)
VALUES ('Regis', 35, '00000000000', 'regis@email.com', '11-98765-4321', 'Sao Paulo', 'SP', '2014-06-08')
""")

cursor.execute("""
INSERT INTO clientes (nome, idade, cpf, email, fone, cidade, uf, criado_em)
VALUES ('Aloisio', 87, '11111111111', 'aloisio@email.com', '98765-4322', 'Porto Alegre', 'RS', '2014-06-09')
""")

cursor.execute("""
INSERT INTO clientes (nome, idade, cpf, email, fone, cidade, uf, criado_em)
VALUES ('Bruna', 21, '22222222222', 'bruna@email.com', '21-98765-4323', 'Rio de Janeiro', 'RJ', '2014-06-09')
""")

cursor.execute("""
INSERT INTO clientes (nome, idade, cpf, email, fone, cidade, uf, criado_em)
VALUES ('Matheus', 19, '33333333333', 'matheus@email.com', '11-98765-4324', 'Campinas', 'SP', '2014-06-08')
""")

# gravando no bd
conn.commit()

# criando uma lista de dados
lista = [(
    'Fabio', 23, '44444444444', 'fabio@email.com', '1234-5678', 'Belo Horizonte', 'MG', '2014-06-09'),
    ('Joao', 21, '55555555555', 'joao@email.com',
     '11-1234-5600', 'Sao Paulo', 'SP', '2014-06-09'),
    ('Xavier', 24, '66666666666', 'xavier@email.com', '12-1234-5601', 'Campinas', 'SP', '2014-06-10')]

# inserindo dados na tabela
cursor.executemany("""
INSERT INTO clientes (nome, idade, cpf, email, fone, cidade, uf, criado_em)
VALUES (?,?,?,?,?,?,?,?)
""", lista)

conn.commit()

# desconectando...
conn.close()

In [26]:
import sqlite3

conn = sqlite3.connect('clientes.db')
cursor = conn.cursor()

# lendo os dados
dados = cursor.execute("""
SELECT * FROM clientes;
""")

df = pd.DataFrame(list(dados))

conn.close()

In [27]:
columns = ['ID', 'Nome', 'Idade', 'CPF', 'Email', 'Fone', 'Cidade', 'UF', 'Criado_em']
df.columns = columns
df.head()

ID     Nome  Idade          CPF              Email           Fone  \
0   1    Regis     35  00000000000    regis@email.com  11-98765-4321   
1   2  Aloisio     87  11111111111  aloisio@email.com     98765-4322   
2   3    Bruna     21  22222222222    bruna@email.com  21-98765-4323   
3   4  Matheus     19  33333333333  matheus@email.com  11-98765-4324   
4   5    Fabio     23  44444444444    fabio@email.com      1234-5678   

           Cidade  UF   Criado_em  
0       Sao Paulo  SP  2014-06-08  
1    Porto Alegre  RS  2014-06-09  
2  Rio de Janeiro  RJ  2014-06-09  
3        Campinas  SP  2014-06-08  
4  Belo Horizonte  MG  2014-06-09

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>